apiVersion: v1
kind: Namespace
metadata:
  name: application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clima-app
  namespace: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clima-app
  template:
    metadata:
      labels:
        app: clima-app
    spec:
      containers:
      - name: clima-app
        image: joscloks418/clima-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.opentelemetry.svc.cluster.local:4317"

        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"

        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=clima-app"

        - name: OTEL_METRICS_EXPORTER
          value: "otlp"

        - name: OTEL_TRACES_EXPORTER
          value: "otlp"

---
apiVersion: v1
kind: Service
metadata:
  name: clima-app-service
  namespace: application
spec:
  type: NodePort
  selector:
    app: clima-app
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30010

