apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: cadvisor
  ports:
  - port: 8080        # Puerto del servicio
    targetPort: 8080  # Puerto dentro del contenedor
    nodePort: 30080   # (Opcional) Puedes elegir o dejar que k8s lo asigne
